# Generated by Django 5.0.3 on 2024-04-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='spl_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='spl_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
