# Generated by Django 5.0.3 on 2024-04-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_spl_address_alter_supplier_spl_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='spl_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
